name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -m spacy download it
    - name: download secret
      env:
        SHEET_JSON: ${{ secrets.SHEET_JSON }}
      run: |
        echo "$SHEET_JSON" > sheet-274815-b5805997d72c.json
    - name: salvini parser
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
        TWITTER_TOKEN_SECRET: ${{ secrets.TWITTER_TOKEN_SECRET }}
      run: |
          python parse.py    
    - name: push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Required
        commit_message: Apply automatic changes

        # Optional branch to push to, defaults to the current branch
        branch: master

        # Optional options appended to `git-commit`
        commit_options: '--no-verify --signoff'

        # Optional glob pattern of files which should be added to the commit
        file_pattern: '*.tsv'

        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: Giacomo Nanni Bot
        commit_user_email: gn.nanni@gmail.com
        commit_author: Author <actions@github.com>

        # Optional tag message 
        # Action will create and push a new tag to the remote repository and the defined branch
        tagging_message: 'v1.0.0'

        # Optional options appended to `git-push`
        push_options: '--force'
